import type { MCPServerEntry } from '@/types/mcp-directory'

/**
 * MCP server directory (curated listings; verify install commands against each official README).
 * Host capability notes are heuristic: most stdio servers can be connected via JSON config across editors.
 */
export const MCP_SERVERS: MCPServerEntry[] = [
  // —— Official / reference implementations (Model Context Protocol ecosystem) ——
  {
    slug: 'mcp-server-filesystem',
    name: 'Filesystem',
    summary: 'Read and write files within allowed paths—suited for local codebases and document batch workflows.',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-filesystem /path/to/project',
    useCases: [
      'Inspect source before batch refactors',
      'Generate or update configuration files',
      'Export reports inside a sandbox directory',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-filesystem',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['files', 'local'],
  },
  {
    slug: 'mcp-server-memory',
    name: 'Memory',
    summary: 'Persistent memory backed by a knowledge graph—keeps entities and relationships across sessions.',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-memory',
    useCases: [
      'Long-running project context',
      'Customer and domain terminology glossaries',
      'Task state spanning conversations',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-memory',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['memory', 'kg'],
  },
  {
    slug: 'mcp-server-github',
    name: 'GitHub',
    summary:
      'Work with repositories, issues, and PRs; requires a PAT. (Original reference impl moved to servers-archived; the npm package remains widely used in examples.)',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-github',
    useCases: ['Search PR discussions', 'Draft new issues', 'Summarize differences between branches'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/github',
    packageName: '@modelcontextprotocol/server-github',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['git', 'api'],
  },
  {
    slug: 'mcp-server-gitlab',
    name: 'GitLab',
    summary: 'Query and lightly operate GitLab projects, merge requests, and CI pipelines. (Reference impl archived.)',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-gitlab',
    useCases: [
      'MR review summaries',
      'Locate failing pipeline logs',
      'Sync milestones with issues',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gitlab',
    packageName: '@modelcontextprotocol/server-gitlab',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['git', 'ci'],
  },
  {
    slug: 'mcp-server-git',
    name: 'Git',
    summary:
      'Safe, read-focused local Git operations—status, log, diff, blame, etc. (Python reference impl; uvx recommended.)',
    category: 'official',
    installCommand: 'uvx mcp-server-git',
    useCases: [
      'Pre-commit change summaries',
      'Trace which revision introduced a line',
      'Explain branching strategy',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
    packageName: 'mcp-server-git',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['git', 'local'],
  },
  {
    slug: 'brave-search-mcp-server',
    name: 'Brave Search',
    summary:
      'Brave-maintained search MCP (reference impl relocated from the main MCP repos). Requires a Brave Search API key.',
    category: 'commercial',
    installCommand: 'npx -y @brave/brave-search-mcp-server',
    useCases: [
      'Verify runtime and library versions',
      'Compare competitor features',
      'Scan news or policy headlines',
      'Look up local businesses',
    ],
    repository: 'https://github.com/brave/brave-search-mcp-server',
    packageName: '@brave/brave-search-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'web'],
  },
  {
    slug: 'mcp-server-fetch',
    name: 'Fetch',
    summary: 'HTTP requests to fetch HTML or JSON APIs (watch SSRF and compliance boundaries).',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-fetch',
    useCases: ['Pull OpenAPI specs', 'Monitor public status pages', 'Scrape documentation site outlines'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-fetch',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['http', 'web'],
  },
  {
    slug: 'mcp-server-puppeteer',
    name: 'Puppeteer',
    summary:
      'Headless browser screenshots plus DOM and accessibility trees. (Reference impl archived; consider Playwright for production.)',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-puppeteer',
    useCases: [
      'Capture SPA screenshots',
      'Frontend visual regression comparisons',
      'Capture public pages before login walls',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer',
    packageName: '@modelcontextprotocol/server-puppeteer',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['browser', 'screenshot'],
  },
  {
    slug: 'mcp-server-everything',
    name: 'Everything',
    summary: 'Demo server covering multiple tool types—useful for learning the MCP protocol.',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-everything',
    useCases: ['Debug MCP clients locally', 'Experiment with protocol behavior', 'Teaching demos'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-everything',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['demo', 'debug'],
  },
  {
    slug: 'mcp-server-sequential-thinking',
    name: 'Sequential Thinking',
    summary: 'Guides stepwise reasoning with explicit hypotheses and checks—good for complex decision trees.',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-sequential-thinking',
    useCases: ['Architecture trade-off writeups', 'Root-cause analysis', 'Scheduling under multiple constraints'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-sequential-thinking',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['reasoning', 'workflow'],
  },
  {
    slug: 'mcp-server-time',
    name: 'Time',
    summary: 'Time zone conversion and current-time queries to reduce model “time hallucination.”',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-time',
    useCases: ['Convert schedules across zones', 'Align log timestamps', 'Explain release windows'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-time',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['time', 'utility'],
  },
  {
    slug: 'mcp-server-postgres',
    name: 'PostgreSQL',
    summary: 'Read-only or controlled SQL plus schema introspection (tighten permissions; reference impl archived).',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-postgres postgresql://user:pass@localhost/db',
    useCases: ['Generate data dictionaries', 'Assist slow-query attribution', 'Confirm report field definitions'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/postgres',
    packageName: '@modelcontextprotocol/server-postgres',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['sql', 'db'],
  },
  {
    slug: 'mcp-server-sqlite',
    name: 'SQLite',
    summary: 'Query local SQLite files—handy for single-file analytics and embedded scenarios. (Reference impl archived.)',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-sqlite /path/to/db.sqlite',
    useCases: [
      'Analyze mobile on-device databases',
      'Inspect test fixture databases',
      'Explore offline datasets',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite',
    packageName: '@modelcontextprotocol/server-sqlite',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['sql', 'db'],
  },
  {
    slug: 'slack-mcp-zencoder',
    name: 'Slack',
    summary:
      'Search and post channel messages—successor implementation maintained by Zencoder (original MCP reference server archived).',
    category: 'community',
    installCommand: 'npx -y @zencoderai/slack-mcp-server',
    useCases: ['Summarize on-call channels', 'Archive customer-support threads', 'Draft release announcements'],
    repository: 'https://github.com/zencoderai/slack-mcp-server',
    packageName: '@zencoderai/slack-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['chat', 'api'],
  },
  {
    slug: 'mcp-server-google-maps',
    name: 'Google Maps',
    summary: 'Geocoding, routing, and place lookup (requires a Maps API key; reference impl archived).',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-google-maps',
    useCases: [
      'Compute distances to storefronts',
      'Estimate commute times',
      'Find POIs around event venues',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/google-maps',
    packageName: '@modelcontextprotocol/server-google-maps',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['maps', 'api'],
  },
  {
    slug: 'mcp-server-sentry',
    name: 'Sentry',
    summary: 'Query error events, releases, and grouped issues. (Reference impl archived.)',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-sentry',
    useCases: [
      'Explain production error clusters',
      'Compare releases',
      'Gather context before assigning owners',
    ],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sentry',
    packageName: '@modelcontextprotocol/server-sentry',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['observability', 'api'],
  },
  {
    slug: 'mcp-server-redis',
    name: 'Redis',
    summary: 'Key scan, TTL, type inspection, and read-oriented commands (use read-only creds in production; reference impl archived).',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-redis redis://localhost:6379',
    useCases: ['Review cache key naming', 'Debug session data', 'Describe queue backlogs'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/redis',
    packageName: '@modelcontextprotocol/server-redis',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['cache', 'db'],
  },
  {
    slug: 'kubernetes-mcp-server',
    name: 'Kubernetes / OpenShift',
    summary: 'Maintained under CNCF containers: read-oriented cluster ops tools (supports npx and uvx).',
    category: 'community',
    installCommand: 'npx kubernetes-mcp-server@latest',
    useCases: [
      'Trace why a Pod will not start',
      'Explain HPA behavior',
      'Unified troubleshooting for OpenShift and Kubernetes',
    ],
    repository: 'https://github.com/containers/kubernetes-mcp-server',
    packageName: 'kubernetes-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['k8s', 'ops'],
  },
  {
    slug: 'mcp-server-aws-kb-retrieval',
    name: 'AWS KB Retrieval',
    summary: 'Retrieve enterprise knowledge snippets from Amazon Bedrock Knowledge Bases. (Reference impl archived.)',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-aws-kb-retrieval',
    useCases: ['Internal policy Q&A', 'Product-manual RAG', 'Locate compliance clauses'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/aws-kb-retrieval-server',
    packageName: '@modelcontextprotocol/server-aws-kb-retrieval',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['aws', 'rag'],
  },
  {
    slug: 'mcp-server-gdrive',
    name: 'Google Drive',
    summary: 'List and read Google Drive documents (OAuth). (Reference impl archived.)',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-gdrive',
    useCases: ['Sync requirements docs', 'Search meeting notes', 'Shared spreadsheet metadata'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gdrive',
    packageName: '@modelcontextprotocol/server-gdrive',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['oauth', 'docs'],
  },
  // —— Community (widely used third-party maintainers) ——
  {
    slug: 'mcp-playwright',
    name: 'Playwright (community)',
    summary: 'Browser automation and E2E assistance built on Playwright.',
    category: 'community',
    installCommand: 'npx -y @executeautomation/playwright-mcp-server',
    useCases: ['Probe E2E selectors', 'Screenshots across browsers', 'Replay form fills'],
    repository: 'https://github.com/executeautomation/mcp-playwright',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['browser', 'e2e'],
  },
  {
    slug: 'mcp-server-docker',
    name: 'Docker',
    summary: 'Manage containers, images, and Compose stacks for ops and troubleshooting (Python package; uvx recommended).',
    category: 'community',
    installCommand: 'uvx mcp-server-docker',
    useCases: ['Local stack health checks', 'Explain image layer sizes', 'Debug port conflicts'],
    repository: 'https://github.com/ckreiling/mcp-server-docker',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['docker', 'ops'],
  },
  {
    slug: 'context7-mcp',
    name: 'Context7',
    summary: 'Injects up-to-date library documentation snippets to reduce stale training-data hallucinations.',
    category: 'community',
    installCommand: 'npx -y @upstash/context7-mcp',
    useCases: [
      'New major-version APIs',
      'Framework migration guides',
      'Verify signatures for niche packages',
    ],
    repository: 'https://github.com/upstash/context7',
    packageName: '@upstash/context7-mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['docs', 'llm'],
  },
  {
    slug: 'supabase-mcp',
    name: 'Supabase',
    summary: 'Assist with projects, tables, RLS, and Edge Functions.',
    category: 'community',
    installCommand: 'npx -y @supabase/mcp-server-supabase@latest',
    useCases: ['Review RLS policies', 'Draft migration SQL', 'Discuss realtime subscription design'],
    repository: 'https://github.com/supabase-community/supabase-mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['baas', 'sql'],
  },
  {
    slug: 'linear-mcp',
    name: 'Linear',
    summary: 'Query issues, projects, cycles, and team workflows.',
    category: 'community',
    installCommand: 'npx -y @linear/mcp-server-linear',
    useCases: ['Sprint scope summaries', 'Blocked dependency chains', 'Draft release notes'],
    repository: 'https://github.com/linear/linear',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['pm', 'api'],
  },
  {
    slug: 'notion-mcp',
    name: 'Notion',
    summary: 'Search pages and databases; read and write content blocks (integration token).',
    category: 'community',
    installCommand: 'npx -y @notionhq/notion-mcp-server',
    useCases: ['Sync PRDs', 'Structure meeting notes', 'Cross-link knowledge-base pages'],
    repository: 'https://github.com/makenotion/notion-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['docs', 'api'],
  },
  {
    slug: 'figma-mcp',
    name: 'Figma (desktop)',
    summary: 'Expose design context through Figma Desktop (requires the local app).',
    category: 'community',
    installCommand: 'See Figma Dev Mode MCP docs (enable in the desktop app)',
    useCases: ['Align on component specs', 'Sync design tokens', 'Explain slices and spacing'],
    repository: 'https://www.figma.com/developers',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'limited' },
    tags: ['design', 'local'],
  },
  {
    slug: 'mcp-server-mysql',
    name: 'MySQL',
    summary: 'Read-only SQL and schema browsing (many community implementations—prefer well-starred repos).',
    category: 'community',
    installCommand: 'npx -y @f4ww4z/mcp-mysql-server',
    useCases: ['Document legacy table layouts', 'Explain stored procedures', 'Discuss index recommendations'],
    repository: 'https://github.com/designcomputer/mysql_mcp_server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['sql', 'db'],
  },
  {
    slug: 'mcp-server-mongodb',
    name: 'MongoDB',
    summary: 'Assist with collections, indexes, and aggregation pipelines (read-only accounts).',
    category: 'community',
    installCommand: 'npx -y mongodb-mcp-server',
    useCases: ['Debug aggregations', 'Discuss shard keys', 'Explain schema evolution'],
    repository: 'https://github.com/mongodb-js/mongodb-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['nosql', 'db'],
  },
  {
    slug: 'mcp-server-elasticsearch',
    name: 'Elasticsearch',
    summary: 'Read-only inspection of index mappings, search DSL, and cluster health.',
    category: 'community',
    installCommand: 'uvx mcp-server-elasticsearch  # or see each fork’s README',
    useCases: ['Debug mapping conflicts', 'Explain query performance', 'Review index templates for logs'],
    repository: 'https://github.com/cr7258/elasticsearch-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['search', 'ops'],
  },
  {
    slug: 'mcp-server-github-official-actions',
    name: 'GitHub Actions insights',
    summary: 'Community extensions around Actions runs and workflow YAML (multiple implementations coexist).',
    category: 'community',
    installCommand: 'Search GitHub for "mcp-server-github-actions" and pick an actively maintained repository',
    useCases: ['Summarize failed job logs', 'Explain matrix strategies', 'Suggest reusable workflows'],
    repository: 'https://github.com/topics/mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'unknown' },
    tags: ['ci', 'github'],
  },
  {
    slug: 'mcp-server-home-assistant',
    name: 'Home Assistant',
    summary: 'Assist with smart-home entity state and automation YAML.',
    category: 'community',
    installCommand: 'pip install ha-mcp-server && ha-mcp-server  # per your chosen fork',
    useCases: ['Troubleshoot automations', 'Interpret energy curves', 'Plan device renames'],
    repository: 'https://github.com/tevonsb/homeassistant-mcp',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['iot', 'yaml'],
  },
  {
    slug: 'mcp-server-obsidian',
    name: 'Obsidian',
    summary: 'Local vault notes—links, tags, and full-text search.',
    category: 'community',
    installCommand: 'npx -y obsidian-mcp-server',
    useCases: ['Personal knowledge graphs', 'Chain meeting notes', 'Unify tag taxonomies'],
    repository: 'https://github.com/cyanheads/obsidian-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['notes', 'local'],
  },
  {
    slug: 'mcp-server-discord',
    name: 'Discord',
    summary: 'Bot-based channel history and messaging (minimize granted permissions).',
    category: 'community',
    installCommand: 'npx -y @antvirf/discord-mcp-server',
    useCases: ['Summarize community FAQs', 'Archive ticket channels', 'Draft event announcements'],
    repository: 'https://github.com/antvirf/discord-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['chat', 'api'],
  },
  {
    slug: 'mcp-server-telegram',
    name: 'Telegram',
    summary: 'Bot API wrapper for fetching and sending messages.',
    category: 'community',
    installCommand: 'uvx mcp-server-telegram  # per README',
    useCases: ['Summarize ops alerts', 'Assist customer-service bots', 'Monitor channel subscriptions'],
    repository: 'https://github.com/search?q=telegram+mcp+server&type=repositories',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['chat', 'api'],
  },
  {
    slug: 'mcp-server-twitter-x',
    name: 'X (Twitter) read',
    summary: 'Read-only timelines and posts (respect platform terms and API tiers).',
    category: 'community',
    installCommand: 'Search GitHub for "twitter mcp server" and pick a compliant implementation',
    useCases: ['Rapid sentiment scans', 'Track competitor accounts', 'Collect takes from technical influencers'],
    repository: 'https://developer.x.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['social', 'api'],
  },
  {
    slug: 'mcp-server-weather',
    name: 'Open-Meteo / Weather',
    summary: 'API-key-free forecasts and historical weather (community wrappers).',
    category: 'community',
    installCommand: 'npx -y @mcp-sdk/server-weather  # or use an Open-Meteo MCP fork',
    useCases: ['Plan outdoor events', 'Weather factors in logistics delays', 'Rough energy-load estimates'],
    repository: 'https://open-meteo.com',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['utility', 'api'],
  },
  {
    slug: 'mcp-server-arxiv',
    name: 'arXiv',
    summary: 'Search preprints and abstracts for research assistance.',
    category: 'community',
    installCommand: 'uvx mcp-server-arxiv',
    useCases: ['Kick off literature reviews', 'Benchmark methods sections', 'Expand citation networks'],
    repository: 'https://arxiv.org/help/api',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['science', 'search'],
  },
  {
    slug: 'podman-mcp-server',
    name: 'Podman',
    summary: 'Manage local or remote Podman containers and images (often paired with the Kubernetes MCP).',
    category: 'community',
    installCommand:
      'See https://github.com/manusa/podman-mcp-server README (often via container or local binary)',
    useCases: [
      'Debug rootless containers',
      'Local iteration with OpenShift',
      'Interpret image build logs',
    ],
    repository: 'https://github.com/manusa/podman-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['docker', 'containers'],
  },
  {
    slug: 'mcp-server-perplexity',
    name: 'Perplexity Search',
    summary:
      'Web QA search with citations (requires Perplexity API; package name depends on your chosen open-source wrapper README).',
    category: 'community',
    installCommand: 'Search npm or GitHub for "perplexity mcp server" and pick an actively maintained implementation',
    useCases: ['Trace citations for technical decisions', 'Verify news claims', 'Multi-source comparison briefs'],
    repository: 'https://www.perplexity.ai',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'rag'],
  },
  {
    slug: 'mcp-server-tavily',
    name: 'Tavily',
    summary: 'MCP adapter for Tavily’s LLM-oriented search and extraction APIs.',
    category: 'community',
    installCommand: 'npx -y tavily-mcp',
    useCases: ['Deep-research agents', 'Structured extraction from competitor sites', 'News digests'],
    repository: 'https://github.com/tavily-ai/tavily-mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'agent'],
  },
  {
    slug: 'mcp-server-exa',
    name: 'Exa',
    summary: 'Semantic search and page content retrieval (commercial API).',
    category: 'community',
    installCommand: 'npx -y exa-mcp-server',
    useCases: [
      'Find similar papers or blogs',
      'Locate a company’s public tech-stack page',
      'Discover docs for niche libraries',
    ],
    repository: 'https://github.com/exa-labs/exa-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'api'],
  },
  {
    slug: 'mcp-server-firecrawl',
    name: 'Firecrawl',
    summary: 'Site-wide crawling and Markdown conversion—useful for site-scale context.',
    category: 'community',
    installCommand: 'npx -y firecrawl-mcp',
    useCases: [
      'Mirror doc sites into vector stores',
      'Inventory features across a competitor site',
      'Content audits before migrations',
    ],
    repository: 'https://github.com/mendableai/firecrawl',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['crawl', 'commercial'],
  },
  {
    slug: 'mcp-server-browserbase',
    name: 'Browserbase',
    summary: 'Cloud headless browser sessions for CI and shared team environments.',
    category: 'community',
    installCommand: 'npx -y @browserbasehq/mcp-server-browserbase',
    useCases: [
      'Reproduce bugs in the cloud',
      'Screenshot pipelines without a local GUI',
      'Multi-region access tests',
    ],
    repository: 'https://github.com/browserbase/mcp-server-browserbase',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['browser', 'cloud'],
  },
  {
    slug: 'mcp-server-azure-devops',
    name: 'Azure DevOps',
    summary: 'Query repos, pipelines, and boards; sync status updates.',
    category: 'community',
    installCommand: 'Search GitHub for "azure devops mcp" for Microsoft- or community-maintained builds',
    useCases: [
      'Link PRs with work items',
      'Explain pipeline parameters',
      'Look up artifact paths',
    ],
    repository: 'https://learn.microsoft.com/azure/devops/',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['ci', 'api'],
  },
  {
    slug: 'mcp-server-jira',
    name: 'Jira Cloud',
    summary:
      'Assist with issues, sprints, board columns, and JQL (many community implementations; no single canonical npm name).',
    category: 'community',
    installCommand:
      'Search GitHub for "jira mcp server" or filter the MCP Registry for Atlassian-related entries',
    useCases: ['Map dependencies across projects', 'Release-train scope', 'Clustered bug reports'],
    repository: 'https://www.atlassian.com/software/jira',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['pm', 'api'],
  },
  {
    slug: 'mcp-server-confluence',
    name: 'Confluence',
    summary: 'Search spaces and page trees; export page bodies as model context.',
    category: 'community',
    installCommand: 'Search GitHub for "confluence mcp server"',
    useCases: ['Locate runbooks', 'Mine decision records', 'Outline onboarding for new hires'],
    repository: 'https://www.atlassian.com/software/confluence',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['docs', 'api'],
  },
  {
    slug: 'mcp-server-pulumi',
    name: 'Pulumi',
    summary: 'Explain infrastructure state and preview diffs (community).',
    category: 'community',
    installCommand: 'pulumi mcp serve  # per Pulumi docs',
    useCases: ['Assess impact of IaC changes', 'Explain stack outputs', 'Review policy-as-code'],
    repository: 'https://www.pulumi.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['iac', 'cloud'],
  },
  {
    slug: 'mcp-server-terraform',
    name: 'Terraform / OpenTofu',
    summary: 'Interpret plan output and narrate module dependency graphs.',
    category: 'community',
    installCommand: 'Search GitHub for "terraform mcp server"',
    useCases: [
      'Discuss state drift',
      'Assess risks when upgrading modules',
      'Explain multi-environment workspaces',
    ],
    repository: 'https://github.com/hashicorp/terraform',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['iac', 'cloud'],
  },
  {
    slug: 'mcp-server-cloudflare',
    name: 'Cloudflare',
    summary: 'Read-only or management helpers for Workers, KV, R2, DNS, and more (multiple implementations).',
    category: 'community',
    installCommand: 'npx -y @cloudflare/mcp-server-cloudflare',
    useCases: ['Edge function logs', 'Explain cache rules', 'Check DNS cutovers'],
    repository: 'https://developers.cloudflare.com/agents/model-context-protocol/',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['edge', 'api'],
  },
  {
    slug: 'mcp-server-vercel',
    name: 'Vercel',
    summary: 'Deployments, domains, and serverless function logs.',
    category: 'community',
    installCommand: 'npx -y @vercel/mcp-server',
    useCases: ['Preview-environment diffs', 'Attribute build failures', 'Explain Edge Config'],
    repository: 'https://vercel.com/docs/mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['hosting', 'api'],
  },
  {
    slug: 'mcp-server-netlify',
    name: 'Netlify',
    summary: 'Site builds, deploy history, and form submissions.',
    category: 'community',
    installCommand: 'Search GitHub for "netlify mcp"',
    useCases: [
      'Suggest rollbacks for static sites',
      'Discuss serverless cold starts',
      'Split build caches',
    ],
    repository: 'https://www.netlify.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['hosting', 'api'],
  },
  {
    slug: 'mcp-server-sentry-alternative',
    name: 'Sentry (alt integrations)',
    summary: 'Community enhancements alongside official server-sentry (custom queries, etc.).',
    category: 'community',
    installCommand: 'Prefer official @modelcontextprotocol/server-sentry',
    useCases: ['Custom Discover queries', 'Switch between organizations'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['observability', 'alt'],
  },
  {
    slug: 'mcp-server-prometheus',
    name: 'Prometheus',
    summary: 'Read-only PromQL and scrape-target status queries.',
    category: 'community',
    installCommand: 'Search GitHub for "prometheus mcp server"',
    useCases: [
      'Explain SLO burn rates',
      'Review recording rules',
      'Summarize alert storms',
    ],
    repository: 'https://prometheus.io',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['metrics', 'ops'],
  },
  {
    slug: 'mcp-server-grafana',
    name: 'Grafana',
    summary: 'Retrieve dashboards, panels, and datasource metadata.',
    category: 'community',
    installCommand: 'Search GitHub for "grafana mcp server"',
    useCases: ['Plan dashboard migrations', 'Explain variables and templates', 'Review alert channels'],
    repository: 'https://grafana.com',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['viz', 'ops'],
  },
  {
    slug: 'mcp-server-openapi',
    name: 'OpenAPI / Swagger',
    summary: 'Generate endpoint descriptions and example requests from openapi.json.',
    category: 'community',
    installCommand: 'npx -y @openapi-mcp/server',
    useCases: ['Draft SDKs', 'Brainstorm contract tests', 'Flag deprecated fields'],
    repository: 'https://github.com/search?q=openapi+mcp&type=repositories',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['api', 'docs'],
  },
  {
    slug: 'mcp-server-postman',
    name: 'Postman',
    summary: 'MCP wrappers around exported collections and environments (multiple implementations).',
    category: 'community',
    installCommand: 'See Postman MCP / Newman-related community repositories',
    useCases: ['Move collections into code', 'Contrast environment deltas', 'Document mock servers'],
    repository: 'https://www.postman.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['api', 'testing'],
  },
  {
    slug: 'mcp-server-graphql',
    name: 'GraphQL introspection',
    summary: 'Document schemas for endpoints that allow public introspection.',
    category: 'community',
    installCommand: 'Search GitHub for "graphql mcp server"',
    useCases: [
      'Recommend field pruning on the frontend',
      'Discuss N+1 risks',
      'Explain federation subgraph boundaries',
    ],
    repository: 'https://graphql.org',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['api', 'schema'],
  },
  {
    slug: 'mcp-server-sqlalchemy',
    name: 'SQLAlchemy / ORM helper',
    summary: 'Assist with models and migration scripts inside Python projects (community).',
    category: 'community',
    installCommand: 'uvx mcp-sqlalchemy  # exact package name may vary',
    useCases: ['Review Alembic migrations', 'Relationship loading strategies', 'Map slow queries to ORM calls'],
    repository: 'https://github.com/sqlalchemy/sqlalchemy',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['python', 'orm'],
  },
  {
    slug: 'mcp-server-railway',
    name: 'Railway',
    summary: 'Read-only views of deployments, variables, and usage (community).',
    category: 'community',
    installCommand: 'Search GitHub for "railway mcp"',
    useCases: [
      'Control costs on hobby projects',
      'Discover inter-service URLs',
      'Analyze build-cache hits',
    ],
    repository: 'https://railway.app',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['paas', 'api'],
  },
  {
    slug: 'mcp-server-fly',
    name: 'Fly.io',
    summary: 'Query Machines, volumes, and region placement.',
    category: 'community',
    installCommand: 'Search GitHub for "fly.io mcp"',
    useCases: ['Latency across global regions', 'Plan volume scaling', 'Describe private-network topology'],
    repository: 'https://fly.io',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['edge', 'api'],
  },
  // —— Commercial / paid APIs ——
  {
    slug: 'stripe-mcp',
    name: 'Stripe',
    summary: 'Assist with customers, subscriptions, invoices, and webhook debugging.',
    category: 'commercial',
    installCommand: 'npx -y @stripe/mcp-server',
    useCases: [
      'Explain reconciliation gaps',
      'Walk through subscription lifecycle changes',
      'Design test-clock scenarios',
    ],
    repository: 'https://stripe.com/docs',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['payments', 'api'],
  },
  {
    slug: 'shopify-mcp',
    name: 'Shopify',
    summary: 'Operational tools for products, orders, and store configuration.',
    category: 'commercial',
    installCommand: 'Search Shopify developer docs for "MCP" for official or partner package names',
    useCases: ['Resolve conflicting promos', 'Inventory sync strategies', 'Explain theme JSON templates'],
    repository: 'https://shopify.dev',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['ecommerce', 'api'],
  },
  {
    slug: 'twilio-mcp',
    name: 'Twilio',
    summary: 'Query SMS/voice/Verify resources plus sandbox workflows.',
    category: 'commercial',
    installCommand: 'Search GitHub for "twilio mcp server"',
    useCases: ['Design 2FA flows', 'Troubleshoot delivery issues', 'Review sub-account isolation'],
    repository: 'https://www.twilio.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'unknown' },
    tags: ['comms', 'api'],
  },
  {
    slug: 'snowflake-mcp',
    name: 'Snowflake',
    summary: 'Snowflake Cortex / external MCP integrations (enterprise features follow official docs).',
    category: 'commercial',
    installCommand: 'See Snowflake documentation: Model Context Protocol integration',
    useCases: [
      'Governed data-lake queries',
      'Explain SQL under policy controls',
      'Discover secured views',
    ],
    repository: 'https://www.snowflake.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['warehouse', 'enterprise'],
  },
  {
    slug: 'databricks-mcp',
    name: 'Databricks',
    summary: 'Lakehouse, notebooks, and Unity Catalog–related MCP (follow official releases).',
    category: 'commercial',
    installCommand: 'See Databricks Partner Connect / MCP documentation',
    useCases: ['Explain table lineage', 'Parameterize job templates', 'Compare MLflow experiments'],
    repository: 'https://www.databricks.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['spark', 'enterprise'],
  },
  {
    slug: 'mongodb-atlas-mcp',
    name: 'MongoDB Atlas',
    summary: 'Management-oriented capabilities for Atlas clusters, Search indexes, and Vector Search.',
    category: 'commercial',
    installCommand: 'npx -y mongodb-mcp-server  # Atlas connection string',
    useCases: [
      'Tune vector-search thresholds',
      'Global Writes topology',
      'Plan backup windows',
    ],
    repository: 'https://www.mongodb.com/docs/atlas/',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['nosql', 'cloud'],
  },
  {
    slug: 'aws-mcp-docs',
    name: 'AWS Documentation',
    summary: 'Retrieve AWS documentation snippets and knowledge-base style answers (many products and versions).',
    category: 'commercial',
    installCommand: 'Search AWS documentation or GitHub aws-samples for MCP server',
    useCases: [
      'Craft least-privilege IAM policies',
      'Check service quotas',
      'Cross-region replication patterns',
    ],
    repository: 'https://aws.amazon.com',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['cloud', 'docs'],
  },
  {
    slug: 'gcp-mcp',
    name: 'Google Cloud',
    summary: 'Explain console resources and gcloud output (enterprise / partner MCPs).',
    category: 'commercial',
    installCommand: 'See Google Cloud MCP / Gemini Enterprise integration documentation',
    useCases: [
      'Attribute BigQuery spend',
      'Cloud Run scaling policies',
      'Review VPC firewall rules',
    ],
    repository: 'https://cloud.google.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['cloud', 'enterprise'],
  },
  {
    slug: 'azure-mcp',
    name: 'Microsoft Azure',
    summary: 'MCP adapters for Azure Resource Graph, monitoring, and DevOps pipelines.',
    category: 'commercial',
    installCommand: 'See Microsoft Foundry / Azure MCP preview documentation',
    useCases: [
      'Subscription cost lenses',
      'Key Vault reference chains',
      'Pre-upgrade AKS checklists',
    ],
    repository: 'https://azure.microsoft.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['cloud', 'enterprise'],
  },
  {
    slug: 'openai-mcp-remote',
    name: 'OpenAI Apps / remote MCP',
    summary: 'Remote MCP connectors for the ChatGPT / OpenAI ecosystem (capabilities evolve with the product).',
    category: 'commercial',
    installCommand: 'See OpenAI developer documentation: Connectors & MCP',
    useCases: [
      'One-click SaaS access from ChatGPT',
      'Corporate data-boundary controls',
      'Tool approval workflows',
    ],
    repository: 'https://platform.openai.com',
    hosts: { claudeCode: 'unknown', claudeDesktop: 'unknown', cursor: 'unknown', windsurf: 'unknown' },
    tags: ['remote', 'saas'],
  },
  {
    slug: 'anthropic-remote-mcp',
    name: 'Anthropic remote MCP',
    summary: 'Remote MCP / connector surfaces inside Claude products (follow official changelog).',
    category: 'commercial',
    installCommand: 'See the Anthropic console and Claude Help Center',
    useCases: [
      'Managed enterprise tool catalogs',
      'Align audit logs',
      'Compliant multi-region deployments',
    ],
    repository: 'https://www.anthropic.com',
    hosts: { claudeCode: 'native', claudeDesktop: 'native', cursor: 'unknown', windsurf: 'unknown' },
    tags: ['remote', 'enterprise'],
  },
]

export const MCP_HOST_MATRIX_ROWS: {
  host: string
  description: string
  stdio: string
  sse: string
  oauthTools: string
}[] = [
  {
    host: 'Claude Desktop',
    description:
      'Anthropic desktop client; configure local stdio subprocesses via `claude_desktop_config.json`.',
    stdio: 'Supported (primary)',
    sse: 'Remote MCP / SSE follows official documentation',
    oauthTools: 'Some connectors support OAuth (depends on the MCP)',
  },
  {
    host: 'Claude Code',
    description: 'Terminal agent; manage MCP servers with commands such as `claude mcp add`.',
    stdio: 'Supported',
    sse: 'Remote capabilities expand with releases',
    oauthTools: 'Matches product remote-MCP policies',
  },
  {
    host: 'Cursor',
    description: 'IDE Settings → MCP; declare commands and env vars in JSON.',
    stdio: 'Supported',
    sse: 'See Cursor release notes (URL-style transport improving over time)',
    oauthTools: 'Depends on the specific server implementation',
  },
  {
    host: 'Windsurf',
    description: 'Cascade MCP; workspace or global configuration.',
    stdio: 'Supported',
    sse: 'See Codeium/Windsurf documentation',
    oauthTools: 'Depends on the specific server implementation',
  },
]
