import type { MCPServerEntry } from '@/types/mcp-directory'

/**
 * MCP 服务器目录（精选收录；安装命令以官方 README 为准）。
 * 宿主能力为经验性标注：多数 stdio 服务器在各编辑器中均可通过 JSON 配置接入。
 */
export const MCP_SERVERS: MCPServerEntry[] = [
  // —— 官方 / 参考实现（Model Context Protocol 生态）——
  {
    slug: 'mcp-server-filesystem',
    name: 'Filesystem',
    summary: '在允许的路径内读写文件，适合本地代码库与文档批处理。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-filesystem /path/to/project',
    useCases: ['批量重构前读源码', '生成/更新配置文件', '在沙箱目录内导出报告'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-filesystem',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['files', 'local'],
  },
  {
    slug: 'mcp-server-memory',
    name: 'Memory',
    summary: '基于知识图谱的持久记忆，跨会话保留实体与关系。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-memory',
    useCases: ['长期项目背景', '客户/领域术语表', '跨对话的任务状态'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-memory',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['memory', 'kg'],
  },
  {
    slug: 'mcp-server-github',
    name: 'GitHub',
    summary: '操作仓库、Issue、PR；需 PAT。（原参考实现已归档至 servers-archived，npm 包仍广泛用于示例。）',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-github',
    useCases: ['检索 PR 讨论', '创建草稿 Issue', '对比分支差异说明'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/github',
    packageName: '@modelcontextprotocol/server-github',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['git', 'api'],
  },
  {
    slug: 'mcp-server-gitlab',
    name: 'GitLab',
    summary: 'GitLab 项目、MR、CI 流水线查询与简单操作。（参考实现已归档。）',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-gitlab',
    useCases: ['MR 评审摘要', '流水线失败日志定位', '里程碑与 Issue 同步'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gitlab',
    packageName: '@modelcontextprotocol/server-gitlab',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['git', 'ci'],
  },
  {
    slug: 'mcp-server-git',
    name: 'Git',
    summary: '本地 git 状态、log、diff、blame 等只读/安全操作（Python 参考实现，推荐 uvx）。',
    category: 'official',
    installCommand: 'uvx mcp-server-git',
    useCases: ['提交前变更摘要', '追溯某行引入版本', '分支策略说明'],
    repository: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
    packageName: 'mcp-server-git',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['git', 'local'],
  },
  {
    slug: 'brave-search-mcp-server',
    name: 'Brave Search',
    summary: 'Brave 官方维护的搜索 MCP（原 MCP 仓库参考实现已迁移至此）。需 Brave Search API Key。',
    category: 'commercial',
    installCommand: 'npx -y @brave/brave-search-mcp-server',
    useCases: ['技术栈版本核对', '竞品功能对比', '新闻/政策速览', '本地商户检索'],
    repository: 'https://github.com/brave/brave-search-mcp-server',
    packageName: '@brave/brave-search-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'web'],
  },
  {
    slug: 'mcp-server-fetch',
    name: 'Fetch',
    summary: 'HTTP 请求抓取网页或 JSON API（需注意 SSRF 与合规）。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-fetch',
    useCases: ['拉取 OpenAPI 文档', '监控公开状态页', '抓取文档站点目录'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-fetch',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['http', 'web'],
  },
  {
    slug: 'mcp-server-puppeteer',
    name: 'Puppeteer',
    summary: '无头浏览器截图、DOM 与可访问性树。（参考实现已归档；生产可评估 Playwright 等替代。）',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-puppeteer',
    useCases: ['SPA 页面截图', '前端回归对比', '抓取需登录前的公开页'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer',
    packageName: '@modelcontextprotocol/server-puppeteer',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['browser', 'screenshot'],
  },
  {
    slug: 'mcp-server-everything',
    name: 'Everything',
    summary: '演示用综合服务器，覆盖多种工具类型，便于学习 MCP 协议。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-everything',
    useCases: ['本地调试 MCP 客户端', '协议行为实验', '教学演示'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-everything',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['demo', 'debug'],
  },
  {
    slug: 'mcp-server-sequential-thinking',
    name: 'Sequential Thinking',
    summary: '引导模型分步推理、显式假设与检验，适合复杂决策树。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-sequential-thinking',
    useCases: ['架构权衡文档', '根因分析', '多约束排期'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-sequential-thinking',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['reasoning', 'workflow'],
  },
  {
    slug: 'mcp-server-time',
    name: 'Time',
    summary: '时区转换与当前时间查询，减少模型「幻觉时间」。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-time',
    useCases: ['排期换算', '日志时间对齐', '发布窗口说明'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    packageName: '@modelcontextprotocol/server-time',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['time', 'utility'],
  },
  {
    slug: 'mcp-server-postgres',
    name: 'PostgreSQL',
    summary: '只读/受控 SQL 与 schema introspection（需严格权限；参考实现已归档）。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-postgres postgresql://user:pass@localhost/db',
    useCases: ['数据字典生成', '慢查询归因辅助', '报表字段确认'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/postgres',
    packageName: '@modelcontextprotocol/server-postgres',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['sql', 'db'],
  },
  {
    slug: 'mcp-server-sqlite',
    name: 'SQLite',
    summary: '本地 SQLite 文件查询，适合单文件分析与嵌入式场景。（参考实现已归档。）',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-sqlite /path/to/db.sqlite',
    useCases: ['移动端本地库分析', '单测数据库检查', '离线数据集探索'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite',
    packageName: '@modelcontextprotocol/server-sqlite',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['sql', 'db'],
  },
  {
    slug: 'slack-mcp-zencoder',
    name: 'Slack',
    summary: '频道消息检索与发送；由 Zencoder 维护的继任实现（原 MCP 参考服务器已归档）。',
    category: 'community',
    installCommand: 'npx -y @zencoderai/slack-mcp-server',
    useCases: ['On-call 频道摘要', '客户支持线程归档', '发布通知草稿'],
    repository: 'https://github.com/zencoderai/slack-mcp-server',
    packageName: '@zencoderai/slack-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['chat', 'api'],
  },
  {
    slug: 'mcp-server-google-maps',
    name: 'Google Maps',
    summary: '地理编码、路线与地点检索（需 Maps API Key；参考实现已归档）。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-google-maps',
    useCases: ['门店距离计算', '通勤时间估算', '活动场地周边 POI'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/google-maps',
    packageName: '@modelcontextprotocol/server-google-maps',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['maps', 'api'],
  },
  {
    slug: 'mcp-server-sentry',
    name: 'Sentry',
    summary: '错误事件、Release 与 Issue 聚合查询。（参考实现已归档。）',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-sentry',
    useCases: ['线上异常聚类说明', 'Release 对比', '分配责任人前的上下文'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sentry',
    packageName: '@modelcontextprotocol/server-sentry',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['observability', 'api'],
  },
  {
    slug: 'mcp-server-redis',
    name: 'Redis',
    summary: '键扫描、TTL、类型与只读命令（生产务必只读账号；参考实现已归档）。',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-redis redis://localhost:6379',
    useCases: ['缓存键命名审查', '会话数据排查', '队列 backlog 说明'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/redis',
    packageName: '@modelcontextprotocol/server-redis',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['cache', 'db'],
  },
  {
    slug: 'kubernetes-mcp-server',
    name: 'Kubernetes / OpenShift',
    summary: 'CNCF containers 组织维护：集群资源只读/运维向工具（支持 npx 与 uvx）。',
    category: 'community',
    installCommand: 'npx kubernetes-mcp-server@latest',
    useCases: ['Pod 起不来事件链', 'HPA 行为解释', 'OpenShift 与 K8s 统一排障'],
    repository: 'https://github.com/containers/kubernetes-mcp-server',
    packageName: 'kubernetes-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['k8s', 'ops'],
  },
  {
    slug: 'mcp-server-aws-kb-retrieval',
    name: 'AWS KB Retrieval',
    summary: '检索 Amazon Bedrock Knowledge Bases 中的企业知识片段。（参考实现已归档。）',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-aws-kb-retrieval',
    useCases: ['内部政策问答', '产品手册 RAG', '合规条款定位'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/aws-kb-retrieval-server',
    packageName: '@modelcontextprotocol/server-aws-kb-retrieval',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['aws', 'rag'],
  },
  {
    slug: 'mcp-server-gdrive',
    name: 'Google Drive',
    summary: '列出/读取 Google 云端硬盘中的文档（OAuth）。（参考实现已归档。）',
    category: 'official',
    installCommand: 'npx -y @modelcontextprotocol/server-gdrive',
    useCases: ['需求文档同步', '会议纪要检索', '共享表格元数据'],
    repository: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gdrive',
    packageName: '@modelcontextprotocol/server-gdrive',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['oauth', 'docs'],
  },
  // —— 社区（常用第三方维护）——
  {
    slug: 'mcp-playwright',
    name: 'Playwright (community)',
    summary: '基于 Playwright 的浏览器自动化与 E2E 辅助。',
    category: 'community',
    installCommand: 'npx -y @executeautomation/playwright-mcp-server',
    useCases: ['E2E 选择器探测', '多浏览器截图', '表单填写回放'],
    repository: 'https://github.com/executeautomation/mcp-playwright',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['browser', 'e2e'],
  },
  {
    slug: 'mcp-server-docker',
    name: 'Docker',
    summary: '容器、镜像与 Compose 管理/排障（Python 包，推荐 uvx）。',
    category: 'community',
    installCommand: 'uvx mcp-server-docker',
    useCases: ['本地 stack 健康检查', '镜像层大小解释', '端口占用排查'],
    repository: 'https://github.com/ckreiling/mcp-server-docker',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['docker', 'ops'],
  },
  {
    slug: 'context7-mcp',
    name: 'Context7',
    summary: '为模型注入最新库文档片段，减少过训练版本幻觉。',
    category: 'community',
    installCommand: 'npx -y @upstash/context7-mcp',
    useCases: ['新 major 版本 API', '框架 migration 指南', '冷门包签名核对'],
    repository: 'https://github.com/upstash/context7',
    packageName: '@upstash/context7-mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['docs', 'llm'],
  },
  {
    slug: 'supabase-mcp',
    name: 'Supabase',
    summary: '项目、表、RLS 与 Edge Function 管理辅助。',
    category: 'community',
    installCommand: 'npx -y @supabase/mcp-server-supabase@latest',
    useCases: ['RLS 策略评审', '迁移 SQL 草稿', '实时订阅设计讨论'],
    repository: 'https://github.com/supabase-community/supabase-mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['baas', 'sql'],
  },
  {
    slug: 'linear-mcp',
    name: 'Linear',
    summary: 'Issue、Project、Cycle 与团队工作流查询。',
    category: 'community',
    installCommand: 'npx -y @linear/mcp-server-linear',
    useCases: ['Sprint 范围摘要', '阻塞依赖链', '发布说明草稿'],
    repository: 'https://github.com/linear/linear',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['pm', 'api'],
  },
  {
    slug: 'notion-mcp',
    name: 'Notion',
    summary: '页面与数据库检索、内容块读写（集成令牌）。',
    category: 'community',
    installCommand: 'npx -y @notionhq/notion-mcp-server',
    useCases: ['PRD 同步', '会议记录结构化', '知识库跨页引用'],
    repository: 'https://github.com/makenotion/notion-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['docs', 'api'],
  },
  {
    slug: 'figma-mcp',
    name: 'Figma (desktop)',
    summary: '通过 Figma Desktop 暴露设计上下文（需本地应用）。',
    category: 'community',
    installCommand: '见 Figma Dev Mode MCP 文档（桌面端启用）',
    useCases: ['组件规格对齐', '设计 Token 同步', '切图与间距说明'],
    repository: 'https://www.figma.com/developers',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'limited' },
    tags: ['design', 'local'],
  },
  {
    slug: 'mcp-server-mysql',
    name: 'MySQL',
    summary: '只读 SQL 与 schema 浏览（社区实现多样，选 star 数高者）。',
    category: 'community',
    installCommand: 'npx -y @f4ww4z/mcp-mysql-server',
    useCases: ['遗留系统表结构文档', '存储过程说明', '索引建议讨论'],
    repository: 'https://github.com/designcomputer/mysql_mcp_server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['sql', 'db'],
  },
  {
    slug: 'mcp-server-mongodb',
    name: 'MongoDB',
    summary: '集合、索引与聚合管道辅助（只读账号）。',
    category: 'community',
    installCommand: 'npx -y mongodb-mcp-server',
    useCases: ['聚合调试', '分片键讨论', 'Schema 演化说明'],
    repository: 'https://github.com/mongodb-js/mongodb-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['nosql', 'db'],
  },
  {
    slug: 'mcp-server-elasticsearch',
    name: 'Elasticsearch',
    summary: '索引 mapping、搜索 DSL 与集群健康只读查询。',
    category: 'community',
    installCommand: 'uvx mcp-server-elasticsearch  # 或见各 fork README',
    useCases: ['mapping 冲突排查', '查询性能解释', '日志索引模板审查'],
    repository: 'https://github.com/cr7258/elasticsearch-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['search', 'ops'],
  },
  {
    slug: 'mcp-server-github-official-actions',
    name: 'GitHub Actions insights',
    summary: '围绕 Actions 运行记录、workflow YAML 的社区增强（多实现并存）。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "mcp-server-github-actions" 选用维护活跃仓库',
    useCases: ['失败 job 日志摘要', 'matrix 策略说明', '复用 workflow 建议'],
    repository: 'https://github.com/topics/mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'unknown' },
    tags: ['ci', 'github'],
  },
  {
    slug: 'mcp-server-home-assistant',
    name: 'Home Assistant',
    summary: '智能家居实体状态与自动化 YAML 辅助。',
    category: 'community',
    installCommand: 'pip install ha-mcp-server && ha-mcp-server  # 以所选 fork 为准',
    useCases: ['自动化排错', '能耗曲线解读', '设备重命名规划'],
    repository: 'https://github.com/tevonsb/homeassistant-mcp',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['iot', 'yaml'],
  },
  {
    slug: 'mcp-server-obsidian',
    name: 'Obsidian',
    summary: '本地 vault 笔记链接、标签与全文检索。',
    category: 'community',
    installCommand: 'npx -y obsidian-mcp-server',
    useCases: ['个人知识图谱', '会议笔记串联', '标签体系统一'],
    repository: 'https://github.com/cyanheads/obsidian-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['notes', 'local'],
  },
  {
    slug: 'mcp-server-discord',
    name: 'Discord',
    summary: 'Bot 方式读频道历史、发消息（权限最小化）。',
    category: 'community',
    installCommand: 'npx -y @antvirf/discord-mcp-server',
    useCases: ['社区 FAQ 汇总', '工单频道归档', '活动公告草稿'],
    repository: 'https://github.com/antvirf/discord-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['chat', 'api'],
  },
  {
    slug: 'mcp-server-telegram',
    name: 'Telegram',
    summary: 'Bot API 封装：消息拉取与发送。',
    category: 'community',
    installCommand: 'uvx mcp-server-telegram  # 以 README 为准',
    useCases: ['运维告警摘要', '客服机器人辅助', '频道订阅监控'],
    repository: 'https://github.com/search?q=telegram+mcp+server&type=repositories',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['chat', 'api'],
  },
  {
    slug: 'mcp-server-twitter-x',
    name: 'X (Twitter) read',
    summary: '时间线/推文只读（需遵守平台条款与 API 层级）。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "twitter mcp server" 选用合规实现',
    useCases: ['舆情速览', '竞品账号动态', '技术 KOL 观点收集'],
    repository: 'https://developer.x.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['social', 'api'],
  },
  {
    slug: 'mcp-server-weather',
    name: 'Open-Meteo / Weather',
    summary: '免 Key 天气预报与历史气象（社区封装）。',
    category: 'community',
    installCommand: 'npx -y @mcp-sdk/server-weather  # 或选用 open-meteo mcp fork',
    useCases: ['户外活动排期', '物流延误天气因素', '能源负荷粗估'],
    repository: 'https://open-meteo.com',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['utility', 'api'],
  },
  {
    slug: 'mcp-server-arxiv',
    name: 'arXiv',
    summary: '预印本检索与摘要，适合科研辅助。',
    category: 'community',
    installCommand: 'uvx mcp-server-arxiv',
    useCases: ['文献综述起点', '方法章节对标', '引用链扩展'],
    repository: 'https://arxiv.org/help/api',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['science', 'search'],
  },
  {
    slug: 'podman-mcp-server',
    name: 'Podman',
    summary: '本地/远程 Podman 容器与镜像管理（与 Kubernetes MCP 常组合使用）。',
    category: 'community',
    installCommand: '见 https://github.com/manusa/podman-mcp-server README（多为容器或本地二进制）',
    useCases: ['rootless 容器调试', '与 OpenShift 本地联调', '镜像构建日志解读'],
    repository: 'https://github.com/manusa/podman-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['docker', 'containers'],
  },
  {
    slug: 'mcp-server-perplexity',
    name: 'Perplexity Search',
    summary: '带引用的网页问答式搜索（需 Perplexity API；包名以所选开源封装 README 为准）。',
    category: 'community',
    installCommand: '在 npm 或 GitHub 搜索 "perplexity mcp server" 选用维护活跃的实现',
    useCases: ['技术决策引用链', '新闻核实', '多源对比摘要'],
    repository: 'https://www.perplexity.ai',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'rag'],
  },
  {
    slug: 'mcp-server-tavily',
    name: 'Tavily',
    summary: '面向 LLM 的搜索/提取 API 的 MCP 适配。',
    category: 'community',
    installCommand: 'npx -y tavily-mcp',
    useCases: ['深度研究 Agent', '竞品官网结构化抽取', '新闻简报'],
    repository: 'https://github.com/tavily-ai/tavily-mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'agent'],
  },
  {
    slug: 'mcp-server-exa',
    name: 'Exa',
    summary: '语义搜索与网页内容抓取（商业 API）。',
    category: 'community',
    installCommand: 'npx -y exa-mcp-server',
    useCases: ['找相似论文/博客', '公司官网技术栈页定位', '小众库文档发现'],
    repository: 'https://github.com/exa-labs/exa-mcp-server',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['search', 'api'],
  },
  {
    slug: 'mcp-server-firecrawl',
    name: 'Firecrawl',
    summary: '整站爬取与 Markdown 化，适合构建站点级上下文。',
    category: 'community',
    installCommand: 'npx -y firecrawl-mcp',
    useCases: ['文档站镜像到向量库', '竞品全站功能清单', '迁移前内容盘点'],
    repository: 'https://github.com/mendableai/firecrawl',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['crawl', 'commercial'],
  },
  {
    slug: 'mcp-server-browserbase',
    name: 'Browserbase',
    summary: '云端无头浏览器会话，适合 CI 与团队共享环境。',
    category: 'community',
    installCommand: 'npx -y @browserbasehq/mcp-server-browserbase',
    useCases: ['云端 repro 缺陷', '无本地 GUI 的截图流水线', '多区域访问测试'],
    repository: 'https://github.com/browserbase/mcp-server-browserbase',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['browser', 'cloud'],
  },
  {
    slug: 'mcp-server-azure-devops',
    name: 'Azure DevOps',
    summary: 'Repos、Pipelines、Boards 查询与状态同步。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "azure devops mcp" 选用微软或社区维护版本',
    useCases: ['PR 与 Work Item 关联', '流水线参数说明', '制品库路径查询'],
    repository: 'https://learn.microsoft.com/azure/devops/',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['ci', 'api'],
  },
  {
    slug: 'mcp-server-jira',
    name: 'Jira Cloud',
    summary: 'Issue、Sprint、看板列与 JQL 辅助（多社区实现并存，无单一官方 npm 名）。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "jira mcp server" 或 MCP Registry 筛选 Atlassian 相关条目',
    useCases: ['跨项目依赖梳理', '版本火车范围', '缺陷聚类报告'],
    repository: 'https://www.atlassian.com/software/jira',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['pm', 'api'],
  },
  {
    slug: 'mcp-server-confluence',
    name: 'Confluence',
    summary: '空间与页面树检索、正文导出为模型上下文。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "confluence mcp server"',
    useCases: ['Runbook 定位', '决策记录考古', '新人 onboarding 大纲'],
    repository: 'https://www.atlassian.com/software/confluence',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['docs', 'api'],
  },
  {
    slug: 'mcp-server-pulumi',
    name: 'Pulumi',
    summary: '基础设施状态与预览 diff 说明（社区）。',
    category: 'community',
    installCommand: 'pulumi mcp serve  # 以 Pulumi 文档为准',
    useCases: ['IaC 变更影响', '堆栈输出解释', '策略即代码审查'],
    repository: 'https://www.pulumi.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['iac', 'cloud'],
  },
  {
    slug: 'mcp-server-terraform',
    name: 'Terraform / OpenTofu',
    summary: 'plan 输出解读与模块依赖图文字化。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "terraform mcp server"',
    useCases: ['state 漂移讨论', '模块升级风险评估', '多环境 workspace 说明'],
    repository: 'https://github.com/hashicorp/terraform',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['iac', 'cloud'],
  },
  {
    slug: 'mcp-server-cloudflare',
    name: 'Cloudflare',
    summary: 'Workers、KV、R2、DNS 等资源只读/管理（多实现）。',
    category: 'community',
    installCommand: 'npx -y @cloudflare/mcp-server-cloudflare',
    useCases: ['边缘函数日志', '缓存规则解释', 'DNS 切流检查'],
    repository: 'https://developers.cloudflare.com/agents/model-context-protocol/',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['edge', 'api'],
  },
  {
    slug: 'mcp-server-vercel',
    name: 'Vercel',
    summary: '部署、域名与 Serverless 函数日志查询。',
    category: 'community',
    installCommand: 'npx -y @vercel/mcp-server',
    useCases: ['预览环境 diff', '构建失败归因', 'Edge Config 说明'],
    repository: 'https://vercel.com/docs/mcp',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['hosting', 'api'],
  },
  {
    slug: 'mcp-server-netlify',
    name: 'Netlify',
    summary: '站点构建与部署历史、表单提交等。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "netlify mcp"',
    useCases: ['静态站发布回滚建议', '函数冷启动讨论', '拆分构建缓存'],
    repository: 'https://www.netlify.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['hosting', 'api'],
  },
  {
    slug: 'mcp-server-sentry-alternative',
    name: 'Sentry (alt integrations)',
    summary: '与官方 server-sentry 并存的社区增强（自定义查询等）。',
    category: 'community',
    installCommand: '优先官方 @modelcontextprotocol/server-sentry',
    useCases: ['自定义 Discover 查询', '多组织切换'],
    repository: 'https://github.com/modelcontextprotocol/servers',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['observability', 'alt'],
  },
  {
    slug: 'mcp-server-prometheus',
    name: 'Prometheus',
    summary: 'PromQL 与 target 状态只读查询。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "prometheus mcp server"',
    useCases: ['SLO  burn rate 解释', 'Recording rule 评审', '告警风暴摘要'],
    repository: 'https://prometheus.io',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['metrics', 'ops'],
  },
  {
    slug: 'mcp-server-grafana',
    name: 'Grafana',
    summary: 'Dashboard、Panel 与数据源元数据检索。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "grafana mcp server"',
    useCases: ['面板迁移规划', '变量与模板说明', '告警通知渠道审查'],
    repository: 'https://grafana.com',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['viz', 'ops'],
  },
  {
    slug: 'mcp-server-openapi',
    name: 'OpenAPI / Swagger',
    summary: '从 openapi.json 生成端点说明与示例请求。',
    category: 'community',
    installCommand: 'npx -y @openapi-mcp/server',
    useCases: ['SDK 草稿', '契约测试用例 brainstorm', '废弃字段标注'],
    repository: 'https://github.com/search?q=openapi+mcp&type=repositories',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['api', 'docs'],
  },
  {
    slug: 'mcp-server-postman',
    name: 'Postman',
    summary: '集合与环境变量导出后的 MCP 包装（多实现）。',
    category: 'community',
    installCommand: '见 Postman MCP / Newman 相关社区仓库',
    useCases: ['集合迁移到代码', '环境差异对比', 'Mock 服务说明'],
    repository: 'https://www.postman.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['api', 'testing'],
  },
  {
    slug: 'mcp-server-graphql',
    name: 'GraphQL introspection',
    summary: '对可公开 introspection 的端点生成 schema 文档化描述。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "graphql mcp server"',
    useCases: ['前端字段裁剪建议', 'N+1 风险讨论', '联邦子图边界说明'],
    repository: 'https://graphql.org',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['api', 'schema'],
  },
  {
    slug: 'mcp-server-sqlalchemy',
    name: 'SQLAlchemy / ORM helper',
    summary: 'Python 项目内模型与迁移脚本辅助（社区）。',
    category: 'community',
    installCommand: 'uvx mcp-sqlalchemy  # 以具体包名为准',
    useCases: ['Alembic 迁移审查', '关系加载策略', '慢查询 ORM 映射'],
    repository: 'https://github.com/sqlalchemy/sqlalchemy',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['python', 'orm'],
  },
  {
    slug: 'mcp-server-railway',
    name: 'Railway',
    summary: '服务部署、变量与用量只读（社区）。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "railway mcp"',
    useCases: [' hobby 项目成本控制', '服务间 URL 发现', '构建缓存命中分析'],
    repository: 'https://railway.app',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['paas', 'api'],
  },
  {
    slug: 'mcp-server-fly',
    name: 'Fly.io',
    summary: 'Machines、Volumes、Regions 状态查询。',
    category: 'community',
    installCommand: '在 GitHub 搜索 "fly.io mcp"',
    useCases: ['全球多区域延迟', '卷扩容规划', '私有网络拓扑说明'],
    repository: 'https://fly.io',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['edge', 'api'],
  },
  // —— 商业 / 需付费 API ——
  {
    slug: 'stripe-mcp',
    name: 'Stripe',
    summary: '客户、订阅、发票与 Webhook 调试辅助。',
    category: 'commercial',
    installCommand: 'npx -y @stripe/mcp-server',
    useCases: ['对账差异解释', '订阅生命周期变更', '测试时钟场景设计'],
    repository: 'https://stripe.com/docs',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['payments', 'api'],
  },
  {
    slug: 'shopify-mcp',
    name: 'Shopify',
    summary: '商品、订单与店铺配置的管理向工具。',
    category: 'commercial',
    installCommand: '在 Shopify 开发者文档检索 "MCP" 获取官方或合作伙伴包名',
    useCases: ['促销规则冲突', '库存同步策略', '主题 JSON 模板说明'],
    repository: 'https://shopify.dev',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['ecommerce', 'api'],
  },
  {
    slug: 'twilio-mcp',
    name: 'Twilio',
    summary: '短信/语音/Verify 等资源查询与沙箱辅助。',
    category: 'commercial',
    installCommand: '在 GitHub 搜索 "twilio mcp server"',
    useCases: ['2FA 流程设计', '送达率问题排查', '子账号隔离审查'],
    repository: 'https://www.twilio.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'unknown' },
    tags: ['comms', 'api'],
  },
  {
    slug: 'snowflake-mcp',
    name: 'Snowflake',
    summary: 'Snowflake Cortex / 外部 MCP 集成（企业功能以官方为准）。',
    category: 'commercial',
    installCommand: '见 Snowflake 文档：Model Context Protocol integration',
    useCases: ['受控数据湖查询', '治理策略下的 SQL 解释', '安全视图发现'],
    repository: 'https://www.snowflake.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['warehouse', 'enterprise'],
  },
  {
    slug: 'databricks-mcp',
    name: 'Databricks',
    summary: 'Lakehouse、Notebook 与 Unity Catalog 相关 MCP（以官方发布为准）。',
    category: 'commercial',
    installCommand: '见 Databricks Partner Connect / MCP 文档',
    useCases: ['表血缘说明', 'Job 参数化模板', 'MLflow 实验对比'],
    repository: 'https://www.databricks.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['spark', 'enterprise'],
  },
  {
    slug: 'mongodb-atlas-mcp',
    name: 'MongoDB Atlas',
    summary: 'Atlas 集群、搜索索引与 Vector Search 管理向能力。',
    category: 'commercial',
    installCommand: 'npx -y mongodb-mcp-server  # Atlas 连接串',
    useCases: ['向量检索阈值调参', 'Global Writes 拓扑', '备份窗口规划'],
    repository: 'https://www.mongodb.com/docs/atlas/',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'stdio' },
    tags: ['nosql', 'cloud'],
  },
  {
    slug: 'aws-mcp-docs',
    name: 'AWS Documentation',
    summary: 'AWS 官方文档与知识片段检索类 MCP（多产品、多版本）。',
    category: 'commercial',
    installCommand: '在 AWS 文档或 GitHub aws-samples 搜索 MCP server',
    useCases: ['IAM 最小权限策略', '服务配额核对', '跨区域复制模式'],
    repository: 'https://aws.amazon.com',
    hosts: { claudeCode: 'stdio', claudeDesktop: 'stdio', cursor: 'stdio', windsurf: 'limited' },
    tags: ['cloud', 'docs'],
  },
  {
    slug: 'gcp-mcp',
    name: 'Google Cloud',
    summary: 'GCP 控制台资源与 gcloud 输出解释（企业/合作伙伴 MCP）。',
    category: 'commercial',
    installCommand: '见 Google Cloud MCP / Gemini Enterprise 集成说明',
    useCases: ['BigQuery 成本归因', 'Cloud Run 伸缩策略', 'VPC 防火墙规则审查'],
    repository: 'https://cloud.google.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['cloud', 'enterprise'],
  },
  {
    slug: 'azure-mcp',
    name: 'Microsoft Azure',
    summary: 'Azure 资源图、监控与 DevOps 链路的 MCP 适配。',
    category: 'commercial',
    installCommand: '见 Microsoft Foundry / Azure MCP 预览文档',
    useCases: ['订阅成本透视', 'Key Vault 引用链', 'AKS 升级前检查清单'],
    repository: 'https://azure.microsoft.com',
    hosts: { claudeCode: 'limited', claudeDesktop: 'limited', cursor: 'limited', windsurf: 'unknown' },
    tags: ['cloud', 'enterprise'],
  },
  {
    slug: 'openai-mcp-remote',
    name: 'OpenAI Apps / remote MCP',
    summary: '面向 ChatGPT / OpenAI 生态的远程 MCP 连接器（能力随产品迭代）。',
    category: 'commercial',
    installCommand: '见 OpenAI 开发者文档：Connectors & MCP',
    useCases: ['SaaS 一键接入 ChatGPT', '企业数据边界控制', '工具审批流'],
    repository: 'https://platform.openai.com',
    hosts: { claudeCode: 'unknown', claudeDesktop: 'unknown', cursor: 'unknown', windsurf: 'unknown' },
    tags: ['remote', 'saas'],
  },
  {
    slug: 'anthropic-remote-mcp',
    name: 'Anthropic remote MCP',
    summary: 'Claude 产品侧的远程 MCP / 连接器能力（以官方 changelog 为准）。',
    category: 'commercial',
    installCommand: '见 Anthropic 控制台与 Claude 帮助中心',
    useCases: ['受管企业工具目录', '审计日志对齐', '跨地域合规部署'],
    repository: 'https://www.anthropic.com',
    hosts: { claudeCode: 'native', claudeDesktop: 'native', cursor: 'unknown', windsurf: 'unknown' },
    tags: ['remote', 'enterprise'],
  },
]

export const MCP_HOST_MATRIX_ROWS: {
  host: string
  description: string
  stdio: string
  sse: string
  oauthTools: string
}[] = [
  {
    host: 'Claude Desktop',
    description: 'Anthropic 桌面客户端；`claude_desktop_config.json` 配置本地 stdio 子进程。',
    stdio: '支持（主要方式）',
    sse: '远程 MCP / SSE 能力以官方文档为准',
    oauthTools: '部分连接器支持 OAuth（视具体 MCP）',
  },
  {
    host: 'Claude Code',
    description: '终端内 Agent；`claude mcp add` 等方式管理 MCP 列表。',
    stdio: '支持',
    sse: '远程能力随版本扩展',
    oauthTools: '与产品侧 remote MCP 策略一致',
  },
  {
    host: 'Cursor',
    description: 'IDE 内 Settings → MCP；JSON 声明命令与 env。',
    stdio: '支持',
    sse: '以 Cursor 发布说明为准（URL 型 transport 逐步完善）',
    oauthTools: '取决于具体服务器实现',
  },
  {
    host: 'Windsurf',
    description: 'Cascade MCP；工作区或全局配置。',
    stdio: '支持',
    sse: '以 Codeium/Windsurf 文档为准',
    oauthTools: '取决于具体服务器实现',
  },
]
