import { GradientSection } from '@/components/ui/gradient-section'
import { GlassCard } from '@/components/ui/glass-card'

export const metadata = {
  title: 'Disclaimer',
  description: 'AI Dev Hub Disclaimer. Understand the nature of the information provided on our site, and our policies regarding third-party tools, AI-generated code, and liability.',
}

export default function DisclaimerPage() {
  return (
    <div className="flex flex-col min-h-screen pb-24">
      {/* Hero Section */}
      <GradientSection className="py-20 md:py-28" variant="gradient">
        <div className="container px-4 md:px-6 max-w-4xl mx-auto text-center">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-white mb-6 font-mono">
            Disclaimer
          </h1>
          <p className="text-base md:text-lg text-zinc-300 max-w-2xl mx-auto leading-relaxed">
            Please read this disclaimer carefully before browsing or using any content provided by AI Dev Hub.
          </p>
        </div>
      </GradientSection>

      <div className="container max-w-4xl mx-auto px-4 py-12">
        <GlassCard variant="glass" padding="lg" className="text-zinc-300 space-y-8 leading-relaxed">
          
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-white">1. Accuracy and Timeliness of Information</h2>
            <p>
              AI Dev Hub is committed to providing timely, objective, and accurate information about AI-powered development tools and workflows. However, the AI industry evolves rapidly. Tool features, pricing, licensing agreements, and Model Context Protocol (MCP) specifications are subject to change at any time.
            </p>
            <p>
              All content on this site (including reviews, ratings, configurations, and tutorials) is for educational and reference purposes only. We do not guarantee that the information is always up-to-date, entirely accurate, or error-free. Users should refer to official sources before making purchasing decisions or deploying tools in production.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-white">2. Disclaimer for Third-Party Products and Services</h2>
            <p>
              The third-party AI assistants (e.g., Cursor, Claude Code, GitHub Copilot) and open-source MCP servers featured on this website are owned, operated, and supported by their respective owners.
            </p>
            <p>
              Any action you take by clicking external links to download, register, purchase, or use these tools constitutes a direct relationship between you and the third party. AI Dev Hub assumes no liability for any security vulnerabilities, downtime losses, billing disputes, or commercial conflicts arising from third-party software.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-white">3. Risks of AI-Generated Code and Workflows</h2>
            <p>
              Code and automation scripts generated by AI tools or agents may contain logical bugs, security flaws, or compliance risks regarding third-party open-source licenses.
            </p>
            <p>
              All deployment tutorials, model configurations, and workflows provided on this site are offered on an &quot;as-is&quot; basis. Users are responsible for conducting rigorous code reviews, compliance audits, and sandbox testing before applying them to production systems. AI Dev Hub shall not be liable for any system failures, data loss, code leaks, or patent/copyright disputes resulting from the adoption of our shared code or workflows.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-white">4. Intellectual Property and Copyright</h2>
            <p>
              AI Dev Hub respects the intellectual property rights of all developers. All logos, product screenshots, descriptions, and trademarks of the tools featured on this site belong to their respective copyright owners.
            </p>
            <p>
              These products are featured solely for technical sharing and developer community exchange. If you are a copyright owner and believe that our review or images infringe your rights, please contact us immediately at <a href="mailto:hello@aidevhub.net" className="text-primary hover:underline">hello@aidevhub.net</a>. We will verify and update or remove the content promptly.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-white">5. Force Majeure</h2>
            <p>
              AI Dev Hub shall not be held liable for any temporary service interruptions, data latency, or data loss caused by Internet Service Provider (ISP) maintenance, telecom network adjustments, or force majeure events (e.g., natural disasters, cyber attacks, government regulations). We will make every effort to restore normal operations as soon as possible.
            </p>
          </section>

          <div className="pt-6 border-t border-zinc-800 text-xs text-zinc-500 text-right font-mono">
            Last Updated: May 25, 2026
          </div>

        </GlassCard>
      </div>
    </div>
  )
}
